# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6dfae478810411e254aa2d9390bb404790b28d194e80468383311711772e074c85e229cc852fa8e5c61e13615b81db212ca0921bbcd88f9fbe86ba7c36b67774

test:
  secret_key_base: df040d2f3efd3d00362562a8f6d8d203d061ef64d6dbce6e1bbaad35160a3d9e2181aa3ea79f102d6aef72447542f2007236504b163cbc23a71d05a6caf26895

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
